### ISSUE TITLE
Problem: db_launcher crashes trying to hog default postgres port

### ISSUE THREAD

**Issue by cognivore** [mainmatter/rust-advanced-testing-workshop#3]
# Why?

When pgsql is running on the host system, it will cause the following to happen:

1. PG image shall be downloaded.
2. It shall fail to start.
3. On subsequent attempts to run `db_launcher`, it won't redownload, won't restart, won't check health with `Failed to launch Postgres container: Missing container health field`.
4. To fix this, as of now:
    - Shut down the running pgsql instance
    - `docker rm test_db`
    - Run `cargo run --bin db_launcher` again

# Proposed fix

[This code fixes this by defaulting to port `4725 (RUST)` and respecting environment variables](https://github.com/cognivore/rust-advanced-testing-workshop/blob/bab5efa37a3416eb9633406c7da53c759e7aea68/db_launcher/src/lib.rs).

**Comment by cognivore** [comment]
Sorry it's not a PR, spent too much time configuring OpenSSL :rofl:

**Comment by LukeMathWalker** [comment]
"Solved" this issue by getting rid of `db_launcher` entirely.

**Comment by cognivore** [comment]
Powerful solution!
